name: stash_objectbox
version: 5.0.0
description: >-
  Objectbox storage extension for the stash API. Provides support to store vaults 
  and caches in a Objectbox database
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.9.1
  path: ^1.8.3
  # Other dependencies
  stash: ^5.0.0
  objectbox: ^2.2.0
  flat_buffers: ^2.0.5
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.3
  # Other dependencies
  lints: ^2.1.1
  build_runner: ^2.4.6
  stash_test: ^5.0.0
  objectbox_generator: ^2.2.0