name: stash
version: 1.0.5
description: >-
  Standard caching API for Dart. Defines a common mechanism to create, 
  access, update, and remove information from caches. Provides a in memory
  reference implementation
homepage: https://github.com/ivoleitao/stash

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  time: ^1.3.0
  uuid: ^2.2.2
  quiver: ^2.1.3
  matcher: ^0.12.9
dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  test_coverage: ^0.4.3