name: stash_dio
version: 5.1.0
description: >-
  Dio extension for the stash API. Provides an interceptor that uses
  stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  http_parser: ^4.0.2
  crypto: ^3.0.3
  dio: ^5.4.0
  stash: ^5.0.3
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.25.1
  # Other dependencies
  lints: ^3.0.0
  mocktail: ^1.0.2
  stash_memory: ^5.0.3
  stash_file: ^5.0.3