name: stash_dio
version: 2.0.2
description: >-
  Dio extension for the stash caching API. Provides an interceptor that uses
  Stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_dio

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  http_parser: ^4.0.0
  crypto: ^3.0.1
  dio: ^4.0.0
  stash: ^2.0.2
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  mocktail: ^0.1.1

scripts: derry.yaml