name: stash_cbl
version: 5.0.0
description: >-
  Couchbase Lite storage extension for the stash API. Provides support to store
  vaults and caches in a Couchbase Lite database.
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.3
  # Other dependencies
  cbl: ^2.1.9
  stash: ^5.0.0
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.1
  # Other dependencies
  lints: ^2.1.1
  stash_test: ^5.0.0
  cbl_dart: ^2.2.0
