name: stash_cbl
version: 4.6.0
description: >-
  Couchbase Lite storage extension for the stash API. Provides support to store
  vaults and caches in a Couchbase Lite database.
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.3
  # Other dependencies
  cbl: ^2.1.4
  stash: ^4.5.0
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.21.4
  # Other dependencies
  lints: ^2.0.1
  stash_test: ^4.5.0
  cbl_dart: ^2.1.5
