name: stash_hive
version: 5.0.0
description: >-
  Hive storage extension for the stash caching API. Provides support to store vaults 
  and caches in the Hive database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_hive

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.9.1
  # Other dependencies
  hive: ^2.2.3
  universal_platform: ^1.0.0+1
  stash: ^5.0.0
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.1
  # Other dependencies
  lints: ^2.1.1
  stash_test: ^4.5.3