name: stash_sembast_web
version: 4.5.2
description: >-
  Sembast Web storage extension for the stash API. Provides support to store vaults 
  and caches in a IndexedDB in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  sembast: ^3.4.0+6
  sembast_web: ^2.1.0+4
  stash_sembast: ^4.5.2
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.21.4
  # Other dependencies
  lints: ^2.0.1
  stash: ^4.5.2
  stash_test: ^4.5.2