name: stash_sqlite
version: 5.0.1
description: >-
   storage extension for the stash API. Provides support to store vaults and 
   caches in a sqlite database in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.12.1
  stash: ^5.0.1
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.3
  # Other dependencies
  lints: ^2.1.1
  build_runner: ^2.4.6
  stash_test: ^5.0.1
  drift_dev: ^2.12.1
