name: stash_sembast
version: 5.0.3
description: >-
  Sembast storage extension for the stash API. Provides support to store vaults and 
  caches in the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.10.0
  # Other dependencies
  sembast: ^3.5.0+1
  stash: ^5.0.2
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.9
  # Other dependencies
  lints: ">=2.1.1 <4.0.0"
  stash_test: ^5.0.2
  build_runner: ^2.4.6