name: prerelease
on:
  push:
    branches:
      - prerelease
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install derry
        run: pub global activate derry
      - name: Build
        run: derry build
      - name: Verify
        run: derry verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
      - name: Add pub Credentials
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json
      - name: Publish
        run: derry publish
